name: Download JSON Daily

on:
  # Runs every day at 13:00 UTC, which is 6:00 AM MST if MST is UTC-7
  schedule:
    - cron: '0 13 * * *'
  # Allows you to run the workflow manually from GitHub Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  download-json-file:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Authenticate and obtain session cookie
        run: |
          curl -c cookies.txt -d "identity=${{ secrets.SPACE_TRACK_USERNAME }}&password=${{ secrets.SPACE_TRACK_PASSWORD }}" \
            https://www.space-track.org/ajaxauth/login

      - name: Download Satellite JSON
        run: |
          curl -b cookies.txt -L 'https://www.space-track.org/basicspacedata/query/class/gp/decay_date/null-val/epoch/%3Enow-30/orderby/norad_cat_id/format/json' \
            --output apps/orbital-eye/public/data/satellite-gp.json

      - name: Download Conjunction JSON
        run: |
          curl -b cookies.txt -L 'https://www.space-track.org/basicspacedata/query/class/cdm_public/format/json' \
            --output apps/orbital-eye/public/data/public-conjunction.json

      - name: Commit and push if changed (main branch)
        run: |
          # Configure Git
          git config user.name "github-actions"
          git config user.email "[email protected]"

          # Stage the files
          git add apps/orbital-eye/public/data/satellite-gp.json
          git add apps/orbital-eye/public/data/public-conjunction.json

          # Only commit/push if there is a change
          if git diff --cached --quiet; then
            echo "No changes in data; skipping commit."
          else
            git commit -m "chore: update satellite-gp.json and public-conjunction.json"
            git push
          fi

      - name: Save files to a temporary directory
        run: |
          mkdir -p temp-data
          cp apps/orbital-eye/public/data/satellite-gp.json temp-data/satellite-gp.json
          cp apps/orbital-eye/public/data/public-conjunction.json temp-data/public-conjunction.json

      - name: Switch to gh-pages branch
        run: |
          git fetch origin gh-pages
          git checkout gh-pages

      - name: Copy files to gh-pages data folder
        run: |
          mkdir -p data
          cp temp-data/satellite-gp.json data/satellite-gp.json
          cp temp-data/public-conjunction.json data/public-conjunction.json

      - name: Commit and push changes to gh-pages
        run: |
          git add data/satellite-gp.json data/public-conjunction.json

          if git diff --cached --quiet; then
            echo "No changes in data; skipping commit."
          else
            git commit -m "chore: update satellite-gp.json and public-conjunction.json in gh-pages"
            git push origin gh-pages
          fi
